// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTeamVitAspDotNetCore.Models;

namespace ProjectTeamVitAspDotNetCore.Migrations
{
    [DbContext(typeof(JwelleryContext))]
    partial class JwelleryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Brand", b =>
                {
                    b.Property<string>("BrandId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Category", b =>
                {
                    b.Property<string>("IdCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Certify", b =>
                {
                    b.Property<string>("CertifyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertifyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertifyId");

                    b.ToTable("Certify");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Color", b =>
                {
                    b.Property<string>("ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Dim", b =>
                {
                    b.Property<string>("DimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DimAmt")
                        .HasColumnType("float");

                    b.Property<double>("DimCrt")
                        .HasColumnType("float");

                    b.Property<double>("DimGm")
                        .HasColumnType("float");

                    b.Property<double>("DimPcs")
                        .HasColumnType("float");

                    b.Property<double>("DimRate")
                        .HasColumnType("float");

                    b.Property<double>("DimSize")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimId");

                    b.ToTable("Dim");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.DimInfo", b =>
                {
                    b.Property<string>("DimInfoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimCrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DimImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("DimPrice")
                        .HasColumnType("float");

                    b.Property<string>("DimSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimInfoId");

                    b.ToTable("DimInfo");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Metal", b =>
                {
                    b.Property<string>("MetalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MetalCrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetalId");

                    b.ToTable("Metal");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailNavigationEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNavigationEmail");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OdId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PdId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OdId");

                    b.HasIndex("PdId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Product", b =>
                {
                    b.Property<string>("PdId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrandId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryIdCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoneId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PdId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryIdCategory");

                    b.HasIndex("ColorId");

                    b.HasIndex("DimId");

                    b.HasIndex("MetalId");

                    b.HasIndex("StoneId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StringRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Stone", b =>
                {
                    b.Property<string>("StoneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("StoneAmt")
                        .HasColumnType("float");

                    b.Property<double>("StoneCrt")
                        .HasColumnType("float");

                    b.Property<double>("StoneGm")
                        .HasColumnType("float");

                    b.Property<double>("StoneRate")
                        .HasColumnType("float");

                    b.HasKey("StoneId");

                    b.ToTable("Stone");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Eable")
                        .HasColumnType("bit");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdRoleNavigationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("IdRoleNavigationId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Order", b =>
                {
                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.User", "EmailNavigation")
                        .WithMany("Order")
                        .HasForeignKey("EmailNavigationEmail");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.OrderDetail", b =>
                {
                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Order", "Od")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OdId");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Product", "Pd")
                        .WithMany("OrderDetail")
                        .HasForeignKey("PdId");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.Product", b =>
                {
                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Brand", "Brand")
                        .WithMany("Product")
                        .HasForeignKey("BrandId");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryIdCategory");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Color", "Color")
                        .WithMany("Product")
                        .HasForeignKey("ColorId");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Dim", "Dim")
                        .WithMany("Product")
                        .HasForeignKey("DimId");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Metal", "Metal")
                        .WithMany("Product")
                        .HasForeignKey("MetalId");

                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Stone", "Stone")
                        .WithMany("Product")
                        .HasForeignKey("StoneId");
                });

            modelBuilder.Entity("ProjectTeamVitAspDotNetCore.Models.User", b =>
                {
                    b.HasOne("ProjectTeamVitAspDotNetCore.Models.Role", "IdRoleNavigation")
                        .WithMany("User")
                        .HasForeignKey("IdRoleNavigationId");
                });
#pragma warning restore 612, 618
        }
    }
}
